export default  {
    //OPERATION
    CREATE_OPERATION:' CREATE_OPERATION',
    UPDATE_OPERATION:'UPDATE_OPERATION',

    //OPERAND
    CREATE_OPERAND:'CREATE_OPERAND',
    UPDATE_OPERAND:'UPDATE_OPERAND',
    

    //COMMON 
    DELETE_ELEMENT:'DELETE_ELEMENT',



    //EDDIT_OPERAND
    SET_INVERSION:'SET_INVERSION',
    SET_NEGATIVE:'SET_NEGATIVE',


}