export default {
    //ADD
    CREATE_TRIANGLE:'ADD_TRIANGLE',

    //DELL
    DELETE_TRIANGLE:'DELETE_TRIANGLE',

    //UPDATE
    UPDATE_TRIANGLE:'UPDATE_TRINAGLE',

    //FORMS
    CLOSE_FORM: 'CLOSE_FORM',
    OPEN_CREATE: 'OPEN_CREATE',
    OPEN_EDIT:'OPEN_EDIT'
    
};